proxy:
  image: nginx
  restart: always
  ports:
  - "443:443"
  links:
  - web
  volumes:
  - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  - ./nginx/sslcert.crt:/etc/nginx/sslcert.crt
  - ./nginx/sslcert.key:/etc/nginx/sslcert.key
web:
  restart: always
  build: ./web
  expose:
    - "5001"
  volumes:
  - ./web:/home/cascade
